### PR TITLE
Add new methods and cover all possible desktop systems

### PR DESCRIPTION
**Pull request by AdrianEddy**
- Updated all dependencies and edition to 2021
- Removed obsolete `extern crate`
- Added `sleep` and `hibernate` functions
- Added proper Linux D-BUS calls
- Added proper MacOS requests via `osascript`

Tested on Windows, macOS, and Linux: Debian/Ubuntu/Arch with GNOME/KDE/xfce4/MATE/Cinnamon

I added method docs in system-specific files, not sure how it'll get rendered for the main crate. If you could check that it would be great

### CODE REVIEW

**Comment by silvioprog** [comment]
Wow, awesome hacking. Thanks a lot for sending this PR! :-)

It worked like a charm in a M1 with macOS Monterey 12.5. Tomorrow I'll test on latest Ubuntu and also provide a Windows 11.

Thank you once again!

**Comment by AdrianEddy** [comment]
@silvioprog Did you have a chance to test this one? It'd be nice to merge and release updated version on crates.io

**Comment by silvioprog** [comment]
Sure @AdrianEddy. I'll provide a Windows machine to test too. I tried to test on Linux, but have to confirm if everything is OK, because I recall I saw a dialog asking to reboot... I'll let you know more details sooner.

**Comment by silvioprog** [comment]
Hey @AdrianEddy, it took some delay, but now I'm with a Windows 11 license to proceed with our tests. 😎
I'll let you know about any update...

**Comment by silvioprog** [comment]
Hey @AdrianEddy, let's merge this. Thank you very much!
Next week I'll try to get some time to test in all supported environments.

**Pull request merged**
